import "~/styles/globals.scss";

import bootstrap from "bootstrap"

import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import { TRPCReactProvider } from "~/trpc/react";
import Footer from "./components/footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
        </head>
        <body className={inter.className}>
          <div className="logo-container container">
            <div className="logo">
              <img src="/../assets/logo-beatbuster.png"></img>
            </div>
          </div>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <Footer></Footer>
        </body>
      </html>
    </ClerkProvider>
  )
}